### ISSUE TITLE
Allowing to fetch existing sink values

### ISSUE THREAD

**Issue by IvanDelsinne** [IvanDelsinne/sinking#4]
The need would be, for example, to have a collector that'd work on some other collector/sink (or collector/sink group) exported data, for example for stats.

**Comment by IvanDelsinne** [comment]
Will probably do a `dependencies` array in collector-specific configuration, which will then be checked on
boot.

There's still a need to resolve the first launch, which will obviously crash for the first collection, as there's "nothing" yet.

- Skipping every dependency-based sink? Bad idea IMHO, due to the fact that a sink could be dependent of another sink, which could also be dependent on something.
- Allowing it to crash at first? Seems like a best-case scenario, but that may be a problem (need some thought)
- Setting "default"s? The most hazardous imho, but that may do.

For the last proposal, a configuration would be required, e.g.

```yaml
collectors:
- sink: depends-on-something
  # ...
  dependencies:
    another-sink: 'default value'
```
